# This workflow will upload a Python Package using Twine when a release is created
# For more information see: https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Upload Python Package

on:
  release:
    types: [published]

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade --no-cache-dir -r requirements.txt
        python -m pip install --upgrade --no-cache-dir --prefer-binary twine
    - name: Bump setup version
      run: python setup_create.py ${{ github.event.release.tag_name }}
    - name: Build wheel
      run: python setup.py sdist bdist_wheel
    - name: Publish package
      run: |
        python -m twine upload "dist/*" -u "__token__" -p ${{ secrets.PYPI_API_TOKEN }}
    - name: Commit version bumped setup.py
      run: |
        git config --global user.email "skillor@gmx.de"
        git config --global user.name "Release Runner"
        git add --force ./setup.py
        git commit -am "Bump release version"
        git tag -fa ${{ github.event.release.tag_name }} -m "Bump to version ${{ github.event.release.tag_name }}"
        git push origin HEAD:master --tags --force
